[project]
name = "sailor"
version = "0.1.0"
description = "A profanity filtering API in Python using regular expressions and FastAPI."
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "inflection>=0.5.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
