name: Check backend

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/api-checks.yml
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - api/**
      - .github/workflows/api-checks.yml

jobs:
  api:
    name: API testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install
        working-directory: api/

      - name: Sync dependencies with uv
        run: uv sync --locked --all-extras --dev
        working-directory: api/

      - name: Run ruff
        run: uvx ruff check
        working-directory: api/

      - name: Run Pytest
        run: uv run pytest
        working-directory: api/
