name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  api:
    name: API testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install
        working-directory: api/

      - name: Sync dependencies with uv
        run: uv sync --locked --all-extras --dev
        working-directory: api/

      - name: Run Pytest
        run: uv run pytest
        working-directory: api/

  www:
    name: Frontend checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install
        working-directory: www/

      - name: Type check
        run: npm run typecheck
        working-directory: www/

      - name: Lint check
        run: npm run lint
        working-directory: www/

      - name: Format check
        run: npm run format:check
        working-directory: www/
