name: Deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - www/**
      - .github/workflows/www-deploy.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  www:
    name: Deploy website
    runs-on: ubuntu-latest
    environment: www

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: www/
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WEBSITE_DEPLOY_TOKEN }}
